In [2]:
import numpy as np

In [4]:
# Import numpy as np and see the version

print(np.__version__)

1.12.1


In [32]:
# create a 1D array
array1 = np.arange(10)
print(array1)

[0 1 2 3 4 5 6 7 8 9]


In [12]:
# create a boolean array
bolArray = np.full((3,3), 1, dtype=bool)
print(bolArray)

[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]


In [33]:
#  extract items that satisfy a given condition from 1D array
extracted = array1[array1 % 2 != 0 ]
print(extracted)


[1 3 5 7 9]


In [39]:
# replace items that satisfy a condition with another value in numpy array
array1[array1 % 2 == 1] = -1
print(array1)
array1 = np.arange(10)

# replace items that satisfy a condition without affecting the original array
replaced = np.where(array1 % 2 != 0, -1, array1)
print(replaced)


[ 0 -1  2 -1  4 -1  6 -1  8 -1]
[ 0 -1  2 -1  4 -1  6 -1  8 -1]


In [41]:
print(array1)
# reshape an array

array1.reshape(2,-1)

[0 1 2 3 4 5 6 7 8 9]


array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [44]:
# stack two arrays vertically
x = [1,2,3]
y = [10,11,12]

z = np.vstack([x,y])
print(z)

[[ 1  2  3]
 [10 11 12]]


In [46]:
# stack two arrays horizontally?
# Difficulty Level: L2

x = [1,2,3]
y = [10,11,12]

z = np.hstack([x,y])
print(z)

[ 1  2  3 10 11 12]


In [52]:
# 10. How to generate custom sequences in numpy without hardcoding?
a =  np.array([1,2,3])
print(a)
one = np.repeat(a,3)
two = np.tile(a,3)
print(np.r_[one, two])

[1 2 3]
[1 1 1 2 2 2 3 3 3 1 2 3 1 2 3 1 2 3]


In [56]:
# How to get the common items between two python numpy arrays
# INTERSECT

a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

inter = np.intersect1d(a,b)
print(inter)

[2 4]


In [57]:
# 12. How to remove from one array those items that exist in another?
# A-B

a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])

np.setdiff1d(a,b)

array([1, 2, 3, 4])

In [60]:
# How to get the positions where elements of two arrays match?


a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

np.where( b == a )
# array a dan b memiliki value yang sama di index berikut ini

(array([1, 3, 5, 7], dtype=int64),)

In [61]:
# 4. How to extract all numbers between a given range from a numpy array?


Object `array` not found.


In [67]:
# 4. How to extract all numbers between a given range from a numpy array
a = np.array([2, 6, 1, 9, 10, 3, 27])
x = np.where((a <=10) & (a >=5))
a[x]

array([ 6,  9, 10])

In [81]:
# 15. How to make a python function that handles scalars to work on numpy arrays?
def maxx(x,y,z):
    "get the max of two items"
    if (x>y) & (x>z):
        return x
    elif (y>x) & (y>z):
        return y
    else:
        return z

maxx(1,5,2)

# membuat suatu fungsi yang memetakan suatu array dari numpy array
pair_max = np.vectorize(maxx, otypes = [float])

a = np.array([5, 7, 9, 8, 6, 4, 5])
b = np.array([6, 3, 4, 8, 9, 7, 1])
c = np.array([7, 8, 4, 8, 9, 7, 1])

pair_max(a,b,c)

array([ 7.,  8.,  9.,  8.,  9.,  7.,  5.])

In [ ]:
# 16. How to swap two columns in a 2d numpy array